version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: unleash-postgres
    environment:
      POSTGRES_USER: unleash
      POSTGRES_PASSWORD: unleash
      POSTGRES_DB: unleash
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unleash"]
      interval: 5s
      timeout: 5s
      retries: 10

  unleash-server:
    image: unleashorg/unleash-server
    container_name: unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://unleash:unleash@postgres:5432/unleash
      DATABASE_SSL: "false"
      UNLEASH_ADMIN_USERNAME: admin
      UNLEASH_ADMIN_PASSWORD: admin
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - spring-net
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:4242/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  unleash-init:
    image: curlimages/curl:8.3.0
    container_name: unleash-init
    depends_on:
      unleash-server:
        condition: service_healthy
    environment:
      ADMIN_TOKEN: "*:development.207c60daac5adad5af6a049179ac7b4cc4df262257702fc3333ef4d6"
    networks:
      - spring-net
    volumes:
      - ./Scripts:/scripts
    entrypoint: ["/bin/sh", "-c", "/scripts/init-flags.sh"]

  product-service:
    build:
      context: ./ProductService
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      unleash-server:
        condition: service_healthy
    environment:
      UNLEASH_API_TOKEN: "*:development.207c60daac5adad5af6a049179ac7b4cc4df262257702fc3333ef4d6"
    networks:
      - spring-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  order-service:
    build:
      context: ./OrderService
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      unleash-server:
        condition: service_healthy
      product-service:
        condition: service_started
    environment:
      UNLEASH_API_TOKEN: "*:development.207c60daac5adad5af6a049179ac7b4cc4df262257702fc3333ef4d6"
    networks:
      - spring-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  spring-net:
    driver: bridge

volumes:
  postgres-data: